service: factle-server

plugins:
  - serverless-offline

package:
  exclude:
    - node_modules/**/aws-sdk/**
    - ./src/**/*.spec.*
    - .eslintrc*
    - .prettierrc*
    - .vscode*
    - README*
    - ./**/__tests__/**
    - .env

custom:
  keepWarm:
    prod: true
    notprod: false

provider:
  name: aws
  runtime: nodejs16.x
  profile: default
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  versionFunctions: false
  endpointType: REGIONAL
  memorySize: 256
  environment:
    SERVERLESS_REGION: ${self:provider.region}
    SERVERLESS_STAGE: ${self:provider.stage}
    SERVERLESS_SERVICE: ${self:service}
    DB_CONNECTION_STR: ${ssm:${self:provider.stage}-db-pass}

functions:
  example:
    handler: src/lambdas/example.handler
  rest-api:
    handler: src/lambdas/rest-api.handler
    timeout: 30
    events:
      - http:
          path: /
          method: any
          cors: true
          private: true
      - http:
          path: /{proxy+}
          method: any
          cors: true
          private: true
      - schedule:
          rate: rate(10 minutes)
          enabled: ${self:custom.keepWarm.${self:provider.stage}, self:custom.keepWarm.notprod}
          input:
            type: warmer
